import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { ApiSpec } from "../types.js";

/**
 * Emit a self-contained MCP server project that, at runtime, behaves
 * identically to `unmcp serve` but is hand-editable. The emitted project
 * embeds the parsed spec and depends only on @modelcontextprotocol/sdk and
 * unmcp-runtime helpers (we ship them as part of the package).
 */
export async function generateProject(
  spec: ApiSpec,
  outDir: string,
  opts: { name?: string; baseUrl?: string } = {}
): Promise<{ files: string[] }> {
  const name = opts.name || sanitizeName(spec.title);
  await mkdir(outDir, { recursive: true });
  await mkdir(join(outDir, "src"), { recursive: true });

  const files: string[] = [];

  // package.json
  const pkg = {
    name,
    version: "0.1.0",
    private: true,
    type: "module",
    bin: { [name]: "./dist/server.js" },
    scripts: {
      build: "tsc",
      start: "node dist/server.js",
    },
    dependencies: {
      "@modelcontextprotocol/sdk": "^1.29.0",
      unmcp: "^0.1.0",
    },
    devDependencies: {
      "@types/node": "^22.0.0",
      typescript: "^5.5.0",
    },
  };
  await writeText(join(outDir, "package.json"), JSON.stringify(pkg, null, 2));
  files.push("package.json");

  // tsconfig.json
  const tsconfig = {
    compilerOptions: {
      target: "ES2022",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      outDir: "./dist",
      rootDir: "./src",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      resolveJsonModule: true,
      declaration: false,
    },
    include: ["src/**/*"],
  };
  await writeText(join(outDir, "tsconfig.json"), JSON.stringify(tsconfig, null, 2));
  files.push("tsconfig.json");

  // Embedded spec.
  await writeText(
    join(outDir, "src", "spec.json"),
    JSON.stringify(spec, null, 2)
  );
  files.push("src/spec.json");

  // Server entry.
  const baseUrlLine = opts.baseUrl
    ? `  baseUrl: ${JSON.stringify(opts.baseUrl)},\n`
    : "";

  const serverTs = `import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { serve } from "unmcp";

const here = dirname(fileURLToPath(import.meta.url));
const spec = JSON.parse(await readFile(join(here, "..", "src", "spec.json"), "utf-8"));

await serve(spec, {
${baseUrlLine}});
`;
  await writeText(join(outDir, "src", "server.ts"), serverTs);
  files.push("src/server.ts");

  // README for the generated project.
  const readme = `# ${name}

MCP server for **${spec.title}** (v${spec.version}).
Generated by [unmcp](https://github.com/unmcp/unmcp).

## Install

\`\`\`bash
npm install
npm run build
\`\`\`

## Run

\`\`\`bash
npm start
\`\`\`

## Configure

Set auth via environment variables before launching:

\`\`\`bash
export UNMCP_BEARER_TOKEN=...   # for HTTP bearer schemes
export UNMCP_API_KEY=...        # for apiKey schemes
\`\`\`

## Customize

The generated server is a thin wrapper around the spec at \`src/spec.json\`.
Edit that file (or replace it entirely) to change the exposed tools.
`;
  await writeText(join(outDir, "README.md"), readme);
  files.push("README.md");

  return { files };
}

async function writeText(path: string, content: string): Promise<void> {
  await writeFile(path, content, "utf-8");
}

function sanitizeName(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 40) || "mcp-server"
  );
}
